name: Deploy to GitHub Pages

on:
  push:
    # main 브랜치에 푸시될 때 배포
    branches:
      - main
    # 수동 실행 가능
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      # ✅ GitHub Actions가 푸시할 수 있도록 권한 부여
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Node.js 버전 지정

      - name: Install dependencies
        run: npm install # 또는 yarn install

      - name: Create .env file # ✅ 환경변수 파일 생성
        run: |
          echo "VITE_MAP_API_KEY=${{ secrets.VITE_MAP_API_KEY }}" > .env

      - name: Build project
        run: npm run build # 또는 yarn build

      # 스테이지 서버 배포 (GitHub Pages)
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # GitHub Pages 배포 브랜치
          folder: dist # Vite의 빌드 결과 폴더 (기본값: dist)

  # 라이브 서버 배포 (NCP Server)
  deploy-to-ncp:
    runs-on: ubuntu-latest
    needs: deploy # GitHub Pages 배포 후 실행
    steps:
      - name: Test SSH Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USER }}
          # key: ${{ secrets.NCP_SSH_KEY }}
          password: ${{ secrets.NCP_PASS }}
          script: |
            echo "SSH Connected Successfully"
            ls -al

      - name: Deploy to NCP Server via SSH
        uses: appleboy/ssh-action@master
        with:
          # NCP 서버 IP
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USER }}
          # GitHub Secrets에 저장된 SSH 키
          # key: ${{ secrets.NCP_SSH_KEY }}
          password: ${{ secrets.NCP_PASS }}
          script: |
            cd /var/www/Visionlife_FE
            git pull origin main
            npm install
            vite build
